const NT={acao:'#e8a030',buki_mao:'#e06060',buki_pe:'#4488dd',direcao:'#8866ee',alvo:'#44aa66',dachi:'#cc8833',ido:'#33aaaa'};
const BS={branca:'#8899bb',laranja:'#cc7722',azul:'#4488ee',amarela:'#ddaa22',verde:'#33aa66',marrom:'#aa6633',kata:'#8844dd',shodan:'#e8d5a3'};
const BELT_ORDER=['branca','laranja','azul','amarela','verde','marrom','shodan'];
let activeBelt='all';
let cvMode='mandala';

const NODES=[
{id:'tsuki',label:'Tsuki',pt:'soco linear',type:'acao',
note:'突き — de 突く, "perfurar, estender". O verbo define o gesto: linear, direto, penetrante. O quadril gira 45° no impacto; o punho rotaciona no final.'},
{id:'uchi',label:'Uchi',pt:'golpe percussivo',type:'acao',
note:'打ち — de 打つ, "bater, percutir". Movimento de chicote ou arco, não linear. A velocidade de retorno é tão importante quanto o impacto.'},
{id:'geri',label:'Geri',pt:'chute',type:'acao',
note:'蹴り — de 蹴る, "chutar". Todo geri tem câmara (joelho sobe primeiro) e extensão. A câmara gera velocidade; sem ela, não é geri.'},
{id:'uke',label:'Uke',pt:'bloqueio',type:'acao',
note:'受け — de 受ける, "receber, aceitar". Bloquear não é parar a força — é recebê-la e redirecionar. O mesmo kanji de "uke" (receber ataque) e "ukemi" (queda segura).'},
{id:'barai',label:'Barai',pt:'varredura',type:'acao',
note:'払い — de 払う, "varrer, limpar". Diferente do uke: afasta o ataque lateralmente em vez de bloqueá-lo frontalmente. Gedan Barai abre o kata de todo o currículo.'},
{id:'keage',label:'Keage',pt:'chicote de perna',type:'acao',
note:'蹴上げ — de 蹴る (chutar) + 上げる (levantar). Chicote de perna para cima sem câmara completa. Velocidade maior que geri; força de impacto menor. Os Sokugi Taikyoku isolam este vocabulário.'},
{id:'seiken',label:'Seiken',pt:'punho frontal',type:'buki_mao',
note:'正拳 — 正 = correto, reto, verdadeiro; 拳 = punho. "O punho correto." Nome prescritivo: não é qualquer punho, mas o formado com precisão — três primeiros nós dos dedos alinhados com o rádio.'},
{id:'uraken',label:'Uraken',pt:'dorso do punho',type:'buki_mao',
note:'裏拳 — 裏 = verso, avesso; 拳 = punho. "Punho invertido." Impacta com os nós do dorso dos dedos. Chicote de retorno — a mão vai e volta, e ambos os movimentos podem ser armas.'},
{id:'tettsui',label:'Tettsui',pt:'punho martelo',type:'buki_mao',
note:'鉄槌 — 鉄 = ferro, aço; 槌 = martelo. "Martelo de ferro." A base do punho cerrado — o lado oposto ao seiken. Impacto descendente ou lateral com massa óssea.'},
{id:'shuto',label:'Shuto',pt:'mão faca',type:'buki_mao',
note:'手刀 — 手 = mão; 刀 = espada, faca. "Faca de mão." A lateral da mão mimética da lâmina. O mesmo gesto corta nos dois sentidos: Shuto Uchi e Shuto Uke usam a mesma superfície.'},
{id:'haito',label:'Haito',pt:'mão crista',type:'buki_mao',
note:'背刀 — 背 = dorso, costas; 刀 = faca. "Faca do dorso." O lado oposto ao shuto — a crista interna da mão. Shuto e Haito são dois gumes da mesma lâmina.'},
{id:'shotei',label:'Shotei',pt:'calcanhar da palma',type:'buki_mao',
note:'掌底 — 掌 = palma; 底 = fundo, base. "Base da palma." O calcanhar da mão: superfície óssea que absorve impacto sem danificar os dedos. Usado em empurrões e bloqueios de pressão.'},
{id:'nukite',label:'Nukite',pt:'lança de dedos',type:'buki_mao',
note:'貫手 — 貫く = penetrar, atravessar; 手 = mão. "Mão que penetra." Dedos estendidos como lança. Requer treino específico de condicionamento dos dedos para uso real.'},
{id:'koken',label:'Koken',pt:'pulso curvado',type:'buki_mao',
note:'弧拳 — 弧 = arco, curva; 拳 = punho. "Punho curvo." O pulso dobrado para cima forma a área de impacto. Alcança alvos que o seiken não alcança — especialmente o rosto em ângulo superior.'},
{id:'empi',label:'Empi',pt:'cotovelo',type:'buki_mao',
note:'猿臂 — 猿 = macaco; 臂 = braço. "Braço de macaco." A velocidade e fluidez do cotovelo evoca o movimento primata. Arma de curta distância com alta densidade de massa óssea.'},
{id:'haishu',label:'Haishu',pt:'dorso da mão aberta',type:'buki_mao',
note:'背手 — 背 = dorso; 手 = mão. "Dorso da mão." Mão aberta com o verso como superfície de impacto. Raro no kihon — aparece principalmente em kata.'},
{id:'chusoku',label:'Chusoku',pt:'meia-pata',type:'buki_pe',
note:'中足 — 中 = meio; 足 = pé. "Meio do pé." A base dos dedos, meia-pata. Superfície primária do Mae Geri e Mawashi Geri. Requer dedos levantados para proteger as falanges.'},
{id:'sokuto',label:'Sokuto',pt:'faca do pé',type:'buki_pe',
note:'足刀 — 足 = pé; 刀 = faca. "Faca do pé." A lateral externa do pé, espelha o shuto. Superfície do Yoko Geri — o pé é a faca, o quadril é o cabo.'},
{id:'kakato',label:'Kakato',pt:'calcanhar',type:'buki_pe',
note:'踵 — "calcanhar." Superfície óssea mais densa do pé. Usado no Ushiro Geri e golpes descendentes (Kakato Otoshi). Impacto com mínima superfície, máxima concentração de força.'},
{id:'haisoku',label:'Haisoku',pt:'peito do pé',type:'buki_pe',
note:'背足 — 背 = dorso; 足 = pé. "Dorso do pé." O peito do pé, arco superior. Usado no Mawashi Geri quando se busca maior alcance e nos Keage circulares.'},
{id:'hiza',label:'Hiza',pt:'joelho',type:'buki_pe',
note:'膝 — "joelho." Arma de curta distância e câmara mínima. Opera no espaço do clinch onde chutes longos são ineficazes. Hiza Geri é o único geri sem extensão completa da perna.'},
{id:'mae',label:'Mae',pt:'frontal',type:'direcao',
note:'前 — "frente, frontal, diante." O vetor primário de toda ofensiva. Mae (frente) define a linha de combate — tudo o mais é variação em relação a este eixo.'},
{id:'mawashi',label:'Mawashi',pt:'circular',type:'direcao',
note:'廻し — de 廻す, "girar, fazer circular." Trajetória de arco gerada pelo quadril como motor. O Mawashi Geri é o chute mais difícil de defender porque não vem de uma linha previsível.'},
{id:'yoko',label:'Yoko',pt:'lateral',type:'direcao',
note:'横 — "lateral, de lado, horizontal." Vetor perpendicular à linha de combate frontal. Yoko Geri usa o sokuto — a "faca do pé" aponta para o lado, o corpo é a haste.'},
{id:'ushiro',label:'Ushiro',pt:'posterior',type:'direcao',
note:'後ろ — "atrás, posterior." O vetor mais raro — exige rotação de 180° do corpo. Alto risco, alto poder: o Ushiro Geri é o chute mais potente do currículo por usar toda a massa corporal.'},
{id:'gyaku',label:'Gyaku',pt:'reverso',type:'direcao',
note:'逆 — "contrário, reverso, oposto." Não é uma direção física, mas relacional: a mão/pé que está atrás na postura. Gyaku Tsuki gira o quadril ao contrário da postura — daí a potência.'},
{id:'soto',label:'Soto',pt:'de fora para dentro',type:'direcao',
note:'外 — "exterior, de fora." Trajetória de fora para dentro — o arco externo. Soto Uke bloqueia cruzando para dentro; Soto Uchi golpeia do lado externo para o centro.'},
{id:'age',label:'Age',pt:'ascendente',type:'direcao',
note:'上げ — de 上げる, "levantar, elevar." O único vetor ascendente do currículo. Age Uke ergue o ataque para cima; Age Zuki soca de baixo para cima. Contrário de Otoshi (descendente).'},
{id:'jodan',label:'Jodan',pt:'nível alto',type:'alvo',
note:'上段 — 上 = alto; 段 = nível, degrau. "Nível alto." Cabeça e rosto. No kumite Kyokushin, socos jodan ao rosto são proibidos — por isso não há Seiken Jodan Tsuki no kihon de contato.'},
{id:'chudan',label:'Chudan',pt:'nível médio',type:'alvo',
note:'中段 — 中 = meio; 段 = nível. "Nível médio." Tronco, costelas e plexo solar. O alvo primário do kumite Kyokushin: costelas flutuantes e fígado são alvos legais e decisivos.'},
{id:'gedan',label:'Gedan',pt:'nível baixo',type:'alvo',
note:'下段 — 下 = baixo; 段 = nível. "Nível baixo." Pernas, abdômen e joelhos. Gedan Barai varre ataques baixos; o Kansetsu Geri visa o joelho no nível gedan.'},
{id:'gammen',label:'Gammen',pt:'rosto',type:'alvo',
note:'顔面 — 顔 = rosto; 面 = face, superfície. "Superfície do rosto." Alvo de socos proibido no kumite Kyokushin por regra — mas ensinado no kihon. A proibição não elimina o vocabulário.'},
{id:'hizo',label:'Hizo',pt:'costela',type:'alvo',
note:'脾臓 — literalmente "baço", mas usado no contexto de flanco/costela flutuante. Alvo preferencial no kumite: a última costela (flutuante) não tem proteção óssea direta.'},
{id:'kansetsu',label:'Kansetsu',pt:'articulação',type:'alvo',
note:'関節 — "articulação, juntura." Kansetsu Geri visa a articulação do joelho — técnica permitida no Kyokushin. Um dos poucos ataques ortogonais à estrutura esquelética no currículo.'},
{id:'zenkutsu',label:'Zenkutsu',pt:'postura avançada',type:'dachi',
note:'前屈立ち — 前 = frente; 屈 = dobrar, curvar; 立ち = postura. "Postura de flexão frontal." 60% do peso na frente. A base primária do kihon e do oi tsuki.'},
{id:'kokutsu',label:'Kokutsu',pt:'postura recuada',type:'dachi',
note:'後屈立ち — 後 = trás; 屈 = dobrar. "Postura de flexão posterior." 70% do peso atrás. Ensina que recuar não é enfraquecer — é mudar o ângulo de força e criar distância de reação.'},
{id:'kiba',label:'Kiba',pt:'postura cavaleiro',type:'dachi',
note:'騎馬立ち — 騎馬 = montar a cavalo; 立ち = postura. "Postura do cavaleiro." Peso igualmente distribuído, joelhos para fora. Força o eixo lateral — nenhuma outra postura treina estabilidade horizontal da mesma forma.'},
{id:'sanchin',label:'Sanchin',pt:'postura ampulheta',type:'dachi',
note:'三戦立ち — 三戦 = três batalhas. "Postura das três batalhas." Pés em ângulo, joelhos para dentro, tensão isométrica contínua. Base do kata Sanchin — o kata isométrico mais antigo do currículo.'},
{id:'kosa',label:'Kosa',pt:'postura cruzada',type:'dachi',
note:'交差立ち — 交差 = cruzar, entrecruzar. "Postura cruzada." Pés cruzados — postura de transição dinâmica. Não é para combate estático: é o passo entre posturas, o momento de pivô.'},
{id:'ayumi',label:'Ayumi',pt:'passo normal',type:'ido',
note:'歩み — "caminhada, passo." De 歩む, "caminhar avançando." O deslocamento padrão: passo alternado, como ao caminhar. Base de todo o ido-geiko — o movimento que conecta técnicas.'},
{id:'okuri',label:'Okuri',pt:'passo deslizante',type:'ido',
note:'送り — de 送る, "enviar, acompanhar." O pé de trás segue o de frente sem cruzar — deslizamento coordenado. Mantém a postura durante o avanço; mais estável que ayumi sob pressão.'},
{id:'tobi',label:'Tobi',pt:'salto',type:'ido',
note:'飛び — de 飛ぶ, "voar, saltar." Deslocamento com fase aérea — máxima explosão de potência. O Tobi no Pinan Sono Go e no Kanku representa a resolução de um impasse de distância pelo ar.'},
];

const TECHS=[
{id:'t01',name:'Seiken Chudan Tsuki',pt:'soco frontal médio',belt:'branca',action:'tsuki',kataOnly:false,
nodes:['seiken','tsuki','mae','chudan'],dachi:'zenkutsu',
desc:'O golpe fundamental. Punho seiken em linha reta ao nível do tronco. Rotação do punho no impacto, quadril 45°.',
exec:'Puxar punho guarda ao quadril. Estender punho de ataque com rotação. Manter tensão no impacto (zanshin).'},
{id:'t02',name:'Seiken Jodan Tsuki',pt:'soco alto',belt:'branca',action:'tsuki',kataOnly:false,
nodes:['seiken','tsuki','mae','jodan'],dachi:'zenkutsu',
desc:'Mesma mecânica do Chudan Tsuki — apenas a linha do punho sobe ao nível do rosto. Jodan é modificador de altura, não técnica nova.',
exec:'Linha do punho ao nível dos olhos. Cotovelo não levanta — o punho lidera.'},
{id:'t03',name:'Seiken Shita Tsuki',pt:'soco ascendente (uppercut)',belt:'branca',action:'tsuki',kataOnly:false,
nodes:['seiken','tsuki','age','chudan'],dachi:'zenkutsu',
desc:'Soco em trajetória ascendente. Punho rotaciona com face para cima. Distância média, força do quadril subindo.',
exec:'Cotovelo aponta ao chão no início. Força vem do quadril subindo, não do braço empurrando.'},
{id:'t04',name:'Seiken Kagi Tsuki',pt:'soco em gancho',belt:'branca',action:'tsuki',kataOnly:false,
nodes:['seiken','tsuki','yoko','jodan'],dachi:'kiba',
desc:'Soco em arco horizontal 90°. Punho impacta com a face lateral. Kiba dachi absorve a rotação. Alvo: têmpora.',
exec:'Braço em arco horizontal, cotovelo dobrado ~90°. Quadril rotaciona no mesmo sentido.'},
{id:'t05',name:'Seiken Ago Uchi',pt:'golpe no queixo',belt:'branca',action:'uchi',kataOnly:false,
nodes:['seiken','uchi','mae','gammen'],dachi:'zenkutsu',
desc:'Golpe ascendente na mandíbula. Tecnicamente uchi (percussão não-linear), não tsuki. Distância curta.',
exec:'Braço sobe em arco vertical curto. Impacto na ponta do queixo com lateral do seiken.'},
{id:'t06',name:'Hiji Uchi',pt:'cotovelada',belt:'branca',action:'uchi',kataOnly:false,
nodes:['empi','uchi','mae','chudan'],dachi:'zenkutsu',
desc:'Cotovelada frontal. O cotovelo é a arma mais dura do corpo. Introdução ao combate de curta distância.',
exec:'Braço dobra ao máximo. Cotovelo impacta em linha reta ao plexo solar. Corpo inteiro avança.'},
{id:'t07',name:'Uraken Gammen Uchi',pt:'dorso do punho no rosto',belt:'branca',action:'uchi',kataOnly:false,
nodes:['uraken','uchi','mae','gammen'],dachi:'zenkutsu',
desc:'Dorso do punho (uraken) golpeia o rosto. Trajetória de chicote — a velocidade do snap é a força.',
exec:'Punho começa junto ao queixo. Braço estende rapidamente e retorna — chicote. Snap no impacto.'},
{id:'t08',name:'Uraken Sayu Uchi',pt:'dorso do punho lateral',belt:'branca',action:'uchi',kataOnly:false,
nodes:['uraken','uchi','yoko','jodan'],dachi:'kiba',
desc:'Uraken em trajetória horizontal lateral. Mesma arma, vetor diferente. Alvo: têmpora ou orelha.',
exec:'Braço em arco horizontal. Uraken golpeia no mesmo eixo do ombro. Kiba dachi estabiliza.'},
{id:'t09',name:'Uraken Hizo Uchi',pt:'dorso do punho na costela',belt:'branca',action:'uchi',kataOnly:false,
nodes:['uraken','uchi','mae','hizo'],dachi:'zenkutsu',
desc:'Uraken descendente à costela. Mesma arma, alvo diferente — demonstra versatilidade do uraken.',
exec:'Punho cai sobre as costelas em arco descendente. Impacto com o dorso. Quadril acompanha.'},
{id:'t10',name:'Uraken Mawashi Uchi',pt:'dorso do punho circular',belt:'branca',action:'uchi',kataOnly:false,
nodes:['uraken','uchi','mawashi','jodan'],dachi:'zenkutsu',
desc:'Uraken em trajetória circular. Primeiro encontro com mawashi como modificador. Alvo: têmpora.',
exec:'Braço em arco circular completo. Cotovelo lidera, punho chicoteia no final do arco.'},
{id:'t11',name:'Shuto Gammen Uchi',pt:'mão faca no rosto',belt:'branca',action:'uchi',kataOnly:false,
nodes:['shuto','uchi','mae','gammen'],dachi:'kokutsu',
desc:'Borda do dedo mínimo (shuto) golpeia o pescoço/lateral do rosto. Kokutsu dachi. O golpe mais versátil do kihon.',
exec:'Mão aberta, dedos juntos. Borda externa lidera. Snap do pulso no impacto.'},
{id:'t12',name:'Shuto Sakotsu Uchi',pt:'mão faca na clavícula',belt:'branca',action:'uchi',kataOnly:false,
nodes:['shuto','uchi','yoko','jodan'],dachi:'kokutsu',
desc:'Shuto descendente à clavícula (sakotsu). Alvo anatômico específico — não snap, mas golpe preciso.',
exec:'Mão faca cai em arco de cima. Impacto perpendicular à clavícula.'},
{id:'t13',name:'Shuto Sakotsu Uchikomi',pt:'mão faca penetrante na clavícula',belt:'branca',action:'uchi',kataOnly:false,
nodes:['shuto','uchi','soto','jodan'],dachi:'kokutsu',
desc:'Versão penetrante (komi) do Sakotsu Uchi. No impacto: mão empurra em vez de retirar.',
exec:'Mesma trajetória. No impacto: mão empurra para dentro. Komi = penetrar no alvo.'},
{id:'t14',name:'Shuto Hizo Uchi',pt:'mão faca na costela',belt:'branca',action:'uchi',kataOnly:false,
nodes:['shuto','uchi','yoko','hizo'],dachi:'kokutsu',
desc:'Shuto lateral à costela/baço. Quarto alvo diferente para a mesma arma shuto.',
exec:'Mão faca vem da guarda lateral. Impacto na costela em arco horizontal.'},
{id:'t15',name:'Shuto Uchi Uchi',pt:'mão faca no pescoço (interno)',belt:'branca',action:'uchi',kataOnly:false,
nodes:['shuto','uchi','soto','jodan'],dachi:'kokutsu',
desc:'Shuto de dentro para fora ao pescoço. Uchi aqui é direção (interno→externo), não ação.',
exec:'Braço começa cruzado ao peito. Mão faca abre em arco de dentro para fora. Alvo: pescoço.'},
{id:'t16',name:'Jodan Uke',pt:'bloqueio alto',belt:'branca',action:'uke',kataOnly:false,
nodes:['uke','age','jodan'],dachi:'zenkutsu',
desc:'Antebraço sobe em diagonal, desviando ataques de cima. O bloqueio desvia — não para o golpe.',
exec:'Antebraço sobe de dentro para fora. Punho acima e à frente da testa no ponto final.'},
{id:'t17',name:'Chudan Soto Uke',pt:'bloqueio médio externo',belt:'branca',action:'uke',kataOnly:false,
nodes:['uke','chudan','soto'],dachi:'zenkutsu',
desc:'Antebraço desce em arco diagonal de fora para dentro, interceptando socos no nível chudan.',
exec:'Antebraço começa alto à lateral. Desce em arco para o centro. Cotovelo ~90° no final.'},
{id:'t18',name:'Chudan Uchi Uke',pt:'bloqueio médio interno',belt:'branca',action:'uke',kataOnly:false,
nodes:['uke','chudan','mae'],dachi:'zenkutsu',
desc:'Bloqueio médio de dentro para fora. Inverso do Soto Uke.',
exec:'Antebraço começa ao quadril oposto. Sobe em arco de dentro para fora.'},
{id:'t19',name:'Gedan Barai',pt:'varredura baixa',belt:'branca',action:'barai',kataOnly:false,
nodes:['barai','gedan','mae'],dachi:'zenkutsu',
desc:'Antebraço desce e abre em diagonal, defendendo ataques baixos. Barai = varrer/desviar.',
exec:'Punho começa ao ombro oposto. Antebraço varre para baixo e fora. Termina ao nível do joelho.'},
{id:'t20',name:'Uchi Uke Gedan Barai',pt:'bloqueio duplo alto+baixo',belt:'branca',action:'uke',kataOnly:false,
nodes:['uke','barai','mae'],dachi:'zenkutsu',
desc:'Combinação simultânea: Uchi Uke com um braço + Gedan Barai com o outro. Defende dois níveis ao mesmo tempo.',
exec:'Ambos os braços em direções opostas simultaneamente. Sincronizar chegada dos dois antebraços.'},
{id:'t21',name:'Mae Keage',pt:'chicote frontal ascendente',belt:'branca',action:'keage',kataOnly:false,
nodes:['keage','haisoku','mae'],dachi:'zenkutsu',
desc:'Keage é chicote de perna esticada, NÃO chute. Perna sobe reta — joelho não dobra como no geri. Haisoku golpeia.',
exec:'Perna sobe RETA — joelho não dobra. Haisoku (peito do pé) chicoteia para cima e retorna.'},
{id:'t22',name:'Uchi Mawashi Geri',pt:'chute circular de dentro p/ fora',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','haisoku','mawashi'],dachi:'zenkutsu',
desc:'Chute circular de dentro para fora. Arco do pé vai de dentro do eixo para fora. Haisoku golpeia.',
exec:'Perna faz arco horizontal de dentro para fora. Joelho lidera, pé segue.'},
{id:'t23',name:'Soto Mawashi Geri',pt:'chute circular de fora p/ dentro',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','haisoku','mawashi'],dachi:'zenkutsu',
desc:'Inverso do Uchi Mawashi — arco de fora para dentro. Mesma arma (haisoku), trajetória oposta.',
exec:'Perna em arco de fora para dentro. Imagem espelhada do Uchi Mawashi.'},
{id:'t24',name:'Hiza Geri',pt:'chute de joelho',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','hiza','mae'],dachi:'zenkutsu',
desc:'Hiza (joelho) como arma — família geri, mas buki é hiza, não pé. Ponto pedagógico fundamental.',
exec:'Joelho sobe ao nível chudan. Alvo: solar plexus. Em clinch: perna não precisa se estender.'},
{id:'t25',name:'Kin Geri',pt:'chute na virilha',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','haisoku','mae'],dachi:'zenkutsu',
desc:'Chute frontal baixo à virilha. Haisoku em trajetória ascendente. Diferente do Mae Geri (buki e alvo distintos).',
exec:'Perna sobe em linha reta, pé estendido. Haisoku impacta à virilha. Snap e retirada.'},
{id:'t26',name:'Mae Geri',pt:'chute frontal',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','chusoku','mae'],dachi:'zenkutsu',
desc:'O chute canônico. Chusoku (meia-pata) com câmara e extensão. A diferença chusoku/haisoku define duas famílias distintas.',
exec:'Câmara: joelho sobe. Extensão: chusoku empurra ao alvo. Câmara de retorno: perna recolhe.'},
{id:'t27',name:'Mawashi Geri',pt:'chute circular',belt:'laranja',action:'geri',kataOnly:false,
nodes:['geri','chusoku','mawashi'],dachi:'zenkutsu',
desc:'Primeiro chute circular. Introduz rotação de quadril em arco — mecanismo diferente de todos os chutes anteriores.',
exec:'Câmara: joelho sobe em diagonal. Quadril abre. Extensão: perna abre em arco. Chusoku impacta.'},
{id:'t28',name:'Yoko Keage',pt:'chicote lateral ascendente',belt:'branca',action:'keage',kataOnly:false,
nodes:['keage','sokuto','yoko'],dachi:'kiba',
desc:'Keage lateral. Sokuto (faca do pé) em arco ascendente lateral. Distinção chicote/chute no eixo lateral.',
exec:'Perna sobe RETA para o lado. Sokuto é a arma. Chicote rápido — sem câmara.'},
{id:'t29',name:'Yoko Geri',pt:'chute lateral',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','sokuto','yoko'],dachi:'kiba',
desc:'Chute lateral com câmara. Sokuto empurra em linha reta para o lado. Câmara lateral: joelho aponta para baixo.',
exec:'Câmara: joelho sobe, ponta voltada ao chão. Extensão: perna empurra horizontalmente. Sokuto perfura.'},
{id:'t30',name:'Kansetsu Geri',pt:'chute na articulação',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','sokuto','kansetsu'],dachi:'zenkutsu',
desc:'Chute ao joelho do oponente com sokuto. Alvo baixo e específico (kansetsu = articulação). Primeiros kata.',
exec:'Sokuto empurra para o lado ao nível do joelho. Força de travamento articular.'},
{id:'t31',name:'Ushiro Geri',pt:'chute posterior',belt:'branca',action:'geri',kataOnly:false,
nodes:['geri','kakato','ushiro'],dachi:'zenkutsu',
desc:'Chute para trás com calcanhar. Espelho pedagógico do Mae Geri — mesma mecânica, direção oposta.',
exec:'Câmara: joelho sobe à frente. Quadril rotaciona 180°. Calcanhar empurra para trás.'},

{id:'t32',name:'Tettsui Uchi',pt:'punho martelo',belt:'azul',action:'uchi',kataOnly:false,
nodes:['tettsui','uchi','yoko'],dachi:'kiba',
desc:'Base inferior do punho (tettsui) cai como martelo. Superfície carnuda, não os nós. Golpe descendente ou lateral.',
exec:'Punho fecha com borda inferior projetada. Golpe como martelo — massa, não snap.'},
{id:'t33',name:'Nukite',pt:'lança de dedos',belt:'azul',action:'tsuki',kataOnly:false,
nodes:['nukite','tsuki','mae'],dachi:'zenkutsu',
desc:'Dedos estendidos como lança. Buki nukite, ação linear (tsuki). Alvo: pontos vitais. Requer condicionamento.',
exec:'Mão aberta, dedos firmes. A mão inteira como arma pontuda. Acelerar no impacto.'},
{id:'t34',name:'Shotei Uchi',pt:'calcanhar da palma',belt:'azul',action:'uchi',kataOnly:false,
nodes:['shotei','uchi','mae'],dachi:'zenkutsu',
desc:'Base da mão aberta golpeia. Superfície sólida, menos risco de lesionar dedos. Tensho usa shotei exclusivamente.',
exec:'Mão abre, dedos dobram para trás. Base carnuda avança. Frontal (empurrar) ou circular.'},
{id:'t35',name:'Morote Uke',pt:'bloqueio reforçado',belt:'azul',action:'uke',kataOnly:false,
nodes:['uke','chudan','mae'],dachi:'zenkutsu',
desc:'Punho do braço de bloqueio apoiado no cotovelo do braço de apoio. Dois braços cooperando em defesa.',
exec:'Um braço bloqueia (Soto Uke), o outro apoia sob o cotovelo. Estrutura rígida.'},
{id:'t36',name:'Mawashi Uke',pt:'bloqueio circular',belt:'azul',action:'uke',kataOnly:false,
nodes:['uke','mawashi','chudan'],dachi:'zenkutsu',
desc:'Antebraço varre em arco circular, redirecionando o ataque. Mawashi como modificador em uke — não só em ataque.',
exec:'Antebraço faz círculo ao nível chudan. Redirecionar, não parar.'},
{id:'t37',name:'Shuto Mawashi Uke',pt:'mão faca bloqueio circular',belt:'azul',action:'uke',kataOnly:false,
nodes:['shuto','uke','mawashi'],dachi:'kokutsu',
desc:'Shuto como buki defensivo. O mesmo buki de 5 ataques distintos aparece em bloqueio circular.',
exec:'Shuto em arco circular de dentro para fora. Kokutsu dachi. Borda da mão redireciona.'},
{id:'t38',name:'Koken Uchi',pt:'pulso curvado',belt:'amarela',action:'uchi',kataOnly:false,
nodes:['koken','uchi','age'],dachi:'zenkutsu',
desc:'Pulso curva (koken = garra) e dorso da mão golpeia em arco. Ponto vital: têmpora, garganta.',
exec:'Pulso curva — mão dobra para baixo, dorso projeta. Koken golpeia em snap. Distância curta.'},
{id:'t39',name:'Haito Uchi',pt:'mão crista',belt:'amarela',action:'uchi',kataOnly:false,
nodes:['haito','uchi','yoko'],dachi:'zenkutsu',
desc:'Borda interna da mão (lado do indicador). Espelho do shuto — shuto usa borda do mínimo, haito usa borda do indicador.',
exec:'Mão aberta, borda interna (indicador) projeta. Arco horizontal. Snap do pulso.'},
{id:'t40',name:'Morote Tsuki',pt:'soco duplo simultâneo',belt:'amarela',action:'tsuki',kataOnly:false,
nodes:['seiken','tsuki','mae','chudan'],dachi:'zenkutsu',
desc:'Ambos os punhos seiken avançam simultaneamente ao chudan. Dobra força — dobra dificuldade de coordenação.',
exec:'Ambos os punhos partem do quadril. Chegam ao chudan no mesmo instante. O quadril empurra os dois.'},
{id:'t41',name:'Koken Uke',pt:'bloqueio com pulso curvado',belt:'amarela',action:'uke',kataOnly:false,
nodes:['koken','uke','chudan'],dachi:'zenkutsu',
desc:'Koken como buki defensivo. Mesma forma de pulso que golpeia em Koken Uchi agora redireciona ataques.',
exec:'Koken desce em arco sobre o ataque. Redirecionar para baixo e lateral.'},
{id:'t42',name:'Juji Uke',pt:'bloqueio em X',belt:'amarela',action:'uke',kataOnly:false,
nodes:['uke','jodan','mae'],dachi:'zenkutsu',
desc:'Dois antebraços cruzados formam X. Defende socos altos ou baixos. Primeiro bloqueio com dois braços em oposição.',
exec:'Ambos os punhos cruzam simultaneamente. Para jodan: sobem juntos. A estrutura X recebe o golpe.'},
{id:'k01',name:'Ura Tsuki',pt:'soco invertido (uppercut curto)',belt:'kata',action:'tsuki',kataOnly:true,
kataSrc:['Saifa','Seienchin'],nodes:['seiken','tsuki','gyaku'],dachi:'zenkutsu',
desc:'Soco com punho invertido (palma para cima). Técnica de clinch — distância mínima. Não canonizado no kihon porque requer contacto.',
exec:'Punho invertido. Soco curto em linha reta. Cotovelo quase reto — distância de combate real.'},
{id:'k02',name:'Tate Tsuki',pt:'soco com punho vertical',belt:'kata',action:'tsuki',kataOnly:true,
kataSrc:['Tsuki no Kata'],nodes:['seiken','tsuki','mae'],dachi:'zenkutsu',
desc:'Punho na posição vertical (tate = vertical). Polegar para cima. Mecânica diferente — cotovelo aponta para o lado.',
exec:'Punho vertical, mesmo caminho do tsuki padrão, mas sem rotação final.'},
{id:'k03',name:'Haishu Uchi',pt:'dorso da mão aberta',belt:'kata',action:'uchi',kataOnly:true,
kataSrc:['Saifa'],nodes:['haishu','uchi','yoko'],dachi:'kiba',
desc:'Haishu = dorso da mão aberta. Lado oposto do shotei (palma). Raramente praticado fora de kata.',
exec:'Mão aberta, dorso projeta em arco lateral. Similar ao uraken mas com mão aberta.'},
{id:'k04',name:'Ushiro Tsuki',pt:'soco para trás',belt:'kata',action:'tsuki',kataOnly:true,
kataSrc:['Pinan Sono San'],nodes:['seiken','tsuki','ushiro'],dachi:'kiba',
desc:'Soco com seiken disparado para trás. Kiba dachi com rotação de quadril inversa. Contra-ataque a agarrada por trás.',
exec:'Em kiba dachi: punho dispara para trás, o outro bloqueia à frente. Quadril rotaciona para o lado do soco traseiro.'},
{id:'k05',name:'Nidan Geri',pt:'chute duplo sem apoiar o pé',belt:'kata',action:'geri',kataOnly:true,
kataSrc:['Saifa'],nodes:['geri','chusoku','mae'],dachi:'zenkutsu',
desc:'Dois chutes consecutivos com a mesma perna sem pousar. Nidan = dois níveis. Exclusivo de kata.',
exec:'Primeiro chute (gedan). Recolhe sem pousar. Segundo chute (jodan). Força em dois pulsos rápidos.'},
{id:'k06',name:'Otoshi Empi',pt:'cotovelada descendente',belt:'kata',action:'uchi',kataOnly:true,
kataSrc:['Saifa'],nodes:['empi','uchi','age'],dachi:'zenkutsu',
desc:'Otoshi = cair. Cotovelada para baixo sobre o oponente. Usa o peso corporal.',
exec:'Cotovelo sobe e cai com peso. Alvo abaixo: costela, coluna. Usar peso, não força muscular.'},
{id:'k07',name:'Mawashi Empi',pt:'cotovelada circular',belt:'kata',action:'uchi',kataOnly:true,
kataSrc:['Seienchin'],nodes:['empi','uchi','mawashi'],dachi:'kiba',
desc:'Cotovelada em arco circular horizontal. Mawashi aplicado ao empi — cobre ângulo único.',
exec:'Cotovelo em arco horizontal completo. Braço inteiro gira com cotovelo como ponta de lança.'},
{id:'k08',name:'Age Empi',pt:'cotovelada ascendente',belt:'kata',action:'uchi',kataOnly:true,
kataSrc:['Seienchin','Pinan Sono Yon'],nodes:['empi','uchi','age'],dachi:'zenkutsu',
desc:'Cotovelada ascendente. Age = subir. Cotovelo sobe em arco — uppercut de cotovelo. Alvo: queixo.',
exec:'Cotovelo parte da lateral e sobe em arco. O peso do corpo sobe junto.'},
{id:'k09',name:'Kakiwake Uke',pt:'bloqueio em cunha',belt:'kata',action:'uke',kataOnly:true,
kataSrc:['Pinan Sono Yon'],nodes:['uke','jodan','mae'],dachi:'zenkutsu',
desc:'Antebraços se separam de dentro para fora como cunha, dividindo espaço entre dois ataques simultâneos.',
exec:'Ambos os punhos cruzados à frente. Abrir os dois braços simultaneamente para fora.'},
{id:'k10',name:'Kake Uke',pt:'bloqueio em gancho',belt:'kata',action:'uke',kataOnly:true,
kataSrc:['Pinan Sono Yon'],nodes:['uke','mawashi','chudan'],dachi:'kokutsu',
desc:'Pulso curva e captura o ataque em vez de desviá-lo. Kake = ganchar. Desvio para controle.',
exec:'Pulso curva sobre o ataque e engancha. Captura e controla o membro atacante.'},
{id:'k11',name:'Shuto Osae Uke',pt:'mão faca pressionando',belt:'kata',action:'uke',kataOnly:true,
kataSrc:['Pinan Sono Go'],nodes:['shuto','uke','mae'],dachi:'kokutsu',
desc:'Shuto que pressiona o ataque para baixo (osae = suprimir). Suprime em vez de desviar.',
exec:'Shuto desce sobre o ataque e pressiona. Força descendente contínua, não snap.'},
{id:'k12',name:'Teisho Uke',pt:'bloqueio com calcanhar da palma',belt:'kata',action:'uke',kataOnly:true,
kataSrc:['Tensho'],nodes:['shotei','uke','mae'],dachi:'sanchin',
desc:'Bloqueio com teisho (shotei). Em Tensho, todos os bloqueios são teisho — único kata inteiramente de mão aberta.',
exec:'Base da palma avança e redireciona. Suave no contato, firme no controle. Sanchin dachi.'},
];

const KATA=[
{id:'k_tai1',name:'Taikyoku Sono Ichi',belt:'branca',time:'20s',
origin:'Funakoshi (1940s), adaptado por Oyama. Embusen I-gata. O kata que abre todo o currículo.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Gedan Barai','Seiken Chudan Oi Tsuki'],
note:'Apenas dois movimentos, repetidos. Defesa → Ataque. O primeiro gesto do Kyokushin é sempre uma varredura baixa.',
silences:'Sem chutes, sem mão aberta. A restrição radical é a mensagem.',
steps:[
  'Yoi! — musubi dachi · punhos na coxa',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu dachi',
  '  ▶ Antebraço parte do ouvido, varre até a coxa. Quadril gira na chegada.',
  '2. Avança → Migi Seiken Chudan Oi Tsuki',
  '  ▶ Punho estende com rotação final. Mão de puxar ao quadril.',
  '3. Giro dir 180° → Migi Gedan Barai',
  '4. Avança → Hidari Oi Tsuki Chudan',
  '5. Giro esq 90° → Hidari Gedan Barai (braço esq lidera)',
  '6. Avança → Migi Oi Tsuki',
  '7. Avança → Migi Oi Tsuki · KIAI',
  '8. Mawatte! → Hidari Gedan Barai (retorna eixo)',
  '9. Avança → Migi Oi Tsuki',
  '10. Giro dir 180° → Migi Gedan Barai',
  '11. Avança → Hidari Oi Tsuki',
  '12. Giro esq 90° → Hidari Gedan Barai (eixo principal)',
  '13. Avança → Migi Oi Tsuki',
  '14. Avança → Migi Oi Tsuki',
  '15. Avança → Migi Oi Tsuki · KIAI',
  '  ▶ Linha de retorno: mawatte → 3 movimentos simétricos de volta ao yoi.',
  'Mawatte! — Yame!',
]},
{id:'k_tai2',name:'Taikyoku Sono Ni',belt:'branca',time:'20s',
origin:'Mesma estrutura do Sono Ichi. Uma variação: Oi Tsuki jodan em vez de chudan.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Gedan Barai','Seiken Jodan Oi Tsuki'],
note:'Jodan como modificador de altura — não técnica nova, mesma gramática. Os três Taikyoku ensinam que a posição não muda o movimento, só o vetor.',
silences:'Sem chutes, sem mão aberta. A altura do alvo é o único modificador — gramática constante, endereço diferente.',
steps:[
  'Yoi! — musubi dachi',
  '  ▶ Estrutura idêntica ao Sono Ichi. Única diferença: tsuki vai ao jodan (rosto).',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu dachi',
  '2. Avança → Migi Seiken Jodan Oi Tsuki',
  '  ▶ Punho ao nível do rosto — requer quadril mais alto e extensão completa do ombro.',
  '3. Giro dir 180° → Migi Gedan Barai',
  '4. Avança → Hidari Jodan Oi Tsuki',
  '5. Giro esq 90° → Hidari Gedan Barai',
  '6. Avança → Migi Jodan Oi Tsuki',
  '7. Avança → Migi Jodan Oi Tsuki · KIAI',
  '8–19. (mesma estrutura do Sono Ichi, tsuki sempre jodan)',
  'Mawatte! — Yame!',
]},
{id:'k_tai3',name:'Taikyoku Sono San',belt:'laranja',time:'22s',
origin:'Terceiro Taikyoku. Introduz Kokutsu Dachi e Chudan Uchi Uke nas viragens laterais.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Gedan Barai','Chudan Uchi Uke','Seiken Jodan Oi Tsuki','Seiken Chudan Oi Tsuki'],
note:'Primeiro kata com duas posturas (Zenkutsu + Kokutsu). Kokutsu ensina que recuar não é enfraquecer — é mudar o ângulo de força.',
silences:'Sem chutes, sem mão aberta. Kokutsu Dachi aparece — mas apenas para recuar, nunca para contra-atacar a partir da postura baixa.',
steps:[
  'Yoi! — musubi dachi',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu dachi',
  '2. Avança → Migi Seiken Chudan Oi Tsuki',
  '3. Giro dir 180° → Migi Gedan Barai · zenkutsu',
  '4. Avança → Hidari Seiken Chudan Oi Tsuki',
  '5. Giro esq 90° → Hidari Chudan Uchi Uke · kokutsu dachi',
  '  ▶ Kokutsu: 70% peso atrás, antebraço bloqueia de dentro para fora.',
  '6. Avança (muda p/ zenkutsu) → Migi Seiken Jodan Oi Tsuki',
  '7. Avança → Migi Seiken Jodan Oi Tsuki · KIAI',
  '8. Mawatte! → Migi Chudan Uchi Uke · kokutsu',
  '9. Avança → Hidari Jodan Oi Tsuki',
  '10. Giro dir 180° → Migi Chudan Uchi Uke · kokutsu',
  '11. Avança → Hidari Jodan Oi Tsuki',
  '12. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '13. Avança → Migi Chudan Oi Tsuki',
  '14. Avança → Migi Chudan Oi Tsuki',
  '15. Avança → Migi Chudan Oi Tsuki · KIAI',
  'Mawatte! — Yame!',
]},
{id:'k_stai1',name:'Sokugi Taikyoku Sono Ichi',belt:'branca',time:'22s',
origin:'Criado por Mas Oyama. Mesmo embusen dos Taikyoku, mas com chutes em vez de socos.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Kansetsu Geri','Mae Keage'],
note:'Este kata separa keage (chicote) de geri (chute). A distinção é mecânica, não nominal.',
silences:'Sem socos. Sem mão aberta. Só pernas.',
steps:[
  'Yoi! — musubi dachi · mãos em guarda baixa',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Kansetsu Geri migi (chute à articulação do joelho)',
  '  ▶ Arma: hiza/sokuto lateral. Alvo: articulação do joelho do adversário.',
  '3. Giro dir 180° → Migi Gedan Barai',
  '4. Kansetsu Geri hidari',
  '5. Giro esq 90° → Hidari Gedan Barai (eixo principal)',
  '6. Mae Keage migi (chicote frontal)',
  '  ▶ Keage ≠ Geri: o pé chicoteia para cima sem câmara, haisoku ou chusoku.',
  '7. Mae Keage migi · KIAI',
  '8–15. (retorno simétrico com Kansetsu Geri + Mae Keage)',
  'Mawatte! — Yame!',
]},
{id:'k_stai2',name:'Sokugi Taikyoku Sono Ni',belt:'branca',time:'22s',
origin:'Variação do Sono Ichi.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Yoko Keage','Mae Keage'],
note:'Yoko Keage substitui Kansetsu Geri — dois vocabulários laterais distintos. Geri vai ao osso; Keage vai à musculatura. Mesma direção, mecânicas opostas.',
silences:'Sem socos, sem mão aberta, sem geri de câmara. Apenas keage — velocidade de perna sem a estrutura completa do chute.',
steps:[
  'Yoi! — musubi dachi',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Yoko Keage migi (chicote lateral)',
  '  ▶ Perna de apoio estável; pé livre chicoteia lateralmente com haisoku.',
  '3. Giro dir 180° → Migi Gedan Barai',
  '4. Yoko Keage hidari',
  '5. Giro esq 90° → Hidari Gedan Barai (eixo principal)',
  '6. Mae Keage migi',
  '7. Mae Keage migi · KIAI',
  '8–15. (retorno: Yoko Keage × 2 cruzamentos + Mae Keage × 3)',
  'Mawatte! — Yame!',
]},
{id:'k_stai3',name:'Sokugi Taikyoku Sono San',belt:'laranja',time:'22s',
origin:'Criado por Mas Oyama como terceira forma da série Sokugi Taikyoku. Introduz combinações de chutes laterais e frontais em sucessão, preparando para o trabalho direcional do Pinan.',
embusen:'M30,80 L30,10 M5,60 L55,60 M5,30 L55,30',
techs:['Mawashi Geri','Mae Keage'],
note:'Primeiro kata com Mawashi Geri — o quadril aprende a orbitar em vez de só estender. O circular é o ataque mais difícil de defender porque não vem de uma linha.',
silences:'Sem socos, sem bloqueios. O circular pressupõe que o quadril já aprendeu a orbitar — nenhum ensino explícito de câmara, só o resultado.',
steps:[
  'Yoi! — musubi dachi',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Migi Mawashi Geri chudan',
  '  ▶ Câmara lateral; quadril orbita; impacto com haisoku na costal.',
  '3. Giro dir 180° → Migi Gedan Barai',
  '4. Hidari Mawashi Geri chudan',
  '5. Giro esq 90° → Hidari Gedan Barai (eixo principal)',
  '6. Migi Mae Keage',
  '7. Migi Mae Keage · KIAI',
  '8–15. (retorno: Mawashi Geri × 2 + Mae Keage × 3)',
  'Mawatte! — Yame!',
]},
{id:'k_pi1',name:'Pinan Sono Ichi',belt:'azul',time:'22s',
origin:'Anko Itosu (1905), modificado por Oyama. Embusen I-gata. Introduz Age Uke e Gyaku Tsuki.',
embusen:'M30,80 L30,10 M5,65 L55,65 M5,15 L55,15',
techs:['Gedan Barai','Jodan Uke','Seiken Chudan Gyaku Tsuki','Seiken Chudan Oi Tsuki'],
note:'Alternância Oi/Gyaku como mecânica de quadril. A base do kumite começa aqui.',
silences:'Sem chutes.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Avança → Migi Seiken Chudan Oi Tsuki',
  '3. Avança → Hidari Seiken Chudan Gyaku Tsuki',
  '  ▶ Gyaku: punho oposto ao pé da frente. Quadril gira na direção do soco.',
  '4. Giro dir 180° → Migi Gedan Barai',
  '5. Avança → Hidari Oi Tsuki',
  '6. Avança → Migi Gyaku Tsuki',
  '7. Giro esq 90° → Hidari Jodan Age Uke · kokutsu dachi',
  '  ▶ Age Uke: antebraço sobe em ângulo 45°, cotovelo na altura do ombro.',
  '8. Avança (zenkutsu) → Migi Oi Tsuki',
  '9. Migi Jodan Age Uke · kokutsu',
  '10. Avança → Hidari Oi Tsuki',
  '11. Migi Jodan Age Uke · kokutsu',
  '12. Avança → Hidari Oi Tsuki · KIAI',
  '13–20. (retorno simétrico pelo braço direito)',
  'Mawatte! — Yame!',
]},
{id:'k_pi2',name:'Pinan Sono Ni',belt:'azul',time:'30s',
origin:'Itosu, adaptado. O kata mais rico em técnicas novas da série Pinan. Introduz Kiba Dachi.',
embusen:'M30,80 L30,50 M30,50 L5,20 M5,20 L55,20 M30,50 L30,10',
techs:['Tettsui Hizo Uchi','Yoko Geri','Uraken Jodan Yoko Uchi','Shuto Mawashi Uke','Mae Geri'],
note:'Primeiro kata com Kiba Dachi e Yoko Geri. Kiba força o peso para baixo e para fora — estabilidade lateral que nenhuma outra postura treina da mesma forma.',
silences:'Sem Uke formal. Pinan 2 usa desvio pelo ângulo: Kiba Dachi não bloqueia — muda o plano de conflito inteiro.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Giro esq 45° → Migi Tettsui Hizo Uchi · kiba dachi',
  '  ▶ Punho martelo golpeia à costela. Kiba: pés paralelos, joelhos para fora, peso baixo.',
  '2. Migi Yoko Geri chudan (chute lateral)',
  '  ▶ Câmara levanta joelho; sokuto projeta lateralmente. Não muda postura.',
  '3. Hidari Uraken Jodan Yoko Uchi (dorso do punho ao rosto)',
  '4. Avança → Migi Oi Tsuki chudan',
  '5. Giro dir 90° → Hidari Tettsui Hizo Uchi · kiba dachi',
  '6. Hidari Yoko Geri chudan',
  '7. Migi Uraken Jodan Yoko Uchi',
  '8. Avança → Hidari Oi Tsuki · KIAI',
  '9. Giro esq 90° → Hidari Shuto Mawashi Uke · kokutsu',
  '  ▶ Shuto em arco circular — mão aberta deflecte de fora para dentro.',
  '10. Avança → Migi Mae Geri · zenkutsu',
  '11. Migi Shuto Mawashi Uke · kokutsu',
  '12. Avança → Hidari Mae Geri',
  '13. Migi Shuto Mawashi Uke · kokutsu',
  '14. Avança → Hidari Mae Geri',
  '15. Hidari Oi Tsuki · KIAI',
  'Mawatte! — Yame!',
]},
{id:'k_pi3',name:'Pinan Sono San',belt:'azul',time:'22s',
origin:'Kiba Dachi predomina. Introduz Hiji Uke, Ushiro Hiji Ate e Ushiro Tsuki.',
embusen:'M5,50 L55,50 M20,50 L20,15 M40,50 L40,15',
techs:['Hiji Uke','Ushiro Hiji Ate','Ushiro Tsuki','Uraken Sayu Ganmen Uchi','Yonhon Nukite'],
note:'Kata de combate de curta distância. Ushiro Tsuki é exclusivo deste kata.',
silences:'Sem geri.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Hidari Chudan Uchi Uke + Migi Chudan Uchi Uke (simultâneos, kiba dachi)',
  '  ▶ Hiji Uke: cotovelos de dentro para fora, defendendo duas linhas.',
  '2. Migi Uraken Sayu Ganmen Uchi (dorso do punho → rosto lateral)',
  '3. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '4. Avança → Migi Oi Tsuki chudan',
  '5. Avança → Migi Oi Tsuki chudan',
  '6. Giro dir 180° → Migi Gedan Barai',
  '7. Avança → Hidari Oi Tsuki',
  '8. Avança → Hidari Oi Tsuki · KIAI',
  '9. Giro esq 90° → Yonhon Nukite (4 dedos ao plexo) · zenkutsu · KIAI',
  '  ▶ Nukite: 4 dedos unidos, ataque ao plexo solar. Braço estende completamente.',
  '10. Ushiro Hiji Ate (cotovelo para trás) + Ushiro Tsuki (soco para trás)',
  '  ▶ Combinação de combate de costas: cotovelo primário, soco secundário.',
  '11–16. (retorno simétrico)',
  'Mawatte! — Yame!',
]},
{id:'k_sanchin',name:'Sanchin no Kata',belt:'azul',time:'2min14s',
origin:'Kanryo Higaonna → China. O kata isométrico mais antigo. Apenas três técnicas.',
embusen:'M30,80 L30,10',
techs:['Seiken Chudan Tsuki','Chudan Soto Uke','Chudan Uchi Uke'],
note:'SEM chutes. SEM uchi. A restrição técnica radical é a mensagem — tudo é sobre tensão, respiração e enraizamento.',
silences:'Zero variação técnica. Toda a atenção vai para qualidade de execução e respiração Ibuki.',
steps:[
  'Yoi! — heisoku dachi · respiração inicial (3 ciclos Ibuki)',
  '  ▶ Ibuki: inspiração pelo nariz, expiração forçada pela garganta com tensão total.',
  '1. Avanço: Sanchin dachi hidari (pé esq na frente, pés em "V" interno)',
  '2. Hidari + Migi Seiken Chudan Tsuki (simultâneos ou alternados lentos)',
  '  ▶ Cada soco: expiração tensa. Tensão isométrica em todo o corpo no impacto.',
  '3. Chudan Soto Uke hidari (antebraço de fora para dentro)',
  '4. Chudan Uchi Uke migi (antebraço de dentro para fora)',
  '  ▶ Cada bloqueio acompanhado de respiração Ibuki completa.',
  '5. Avanço: 3 passos em sanchin dachi com tsuki alternados',
  '6. Giro 180° → retorno 3 passos com tsuki alternados',
  '7. Sequência Uke: Soto + Uchi × 3',
  '  ▶ Senssei pode bater no corpo para testar tensão — o practicante não cede.',
  '8. Mawatte! — expiração final longa',
  'Yame! — musubi dachi · inclinação',
]},
{id:'k_pi4',name:'Pinan Sono Yon',belt:'amarela',time:'30s',
origin:'Introduz Juji Uke, Kakiwake Uke, Kosa Dachi, Tsuru Ashi Dachi e Hiza Geri.',
embusen:'M5,50 L55,50 M10,10 L50,10 M10,80 L50,80 M30,50 L30,10',
techs:['Juji Uke','Kakiwake Uke','Empi/Hiji Ate','Hiza Geri','Morote Uke','Nukite'],
note:'Pinan 4 é o kata dos bloqueios compostos: Juji, Kakiwake, Morote — dois braços respondendo juntos. Curta distância, alta complexidade de entrada.',
silences:'Sem socos longos, sem chutes de longa distância. Pinan 4 opera inteiramente em curta distância: joelhos, cotovelos, bloqueios duplos.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Giro esq 90° → Hidari Jodan Age Uke + Migi Chudan Soto Uke (Morote Uke simultâneo)',
  '  ▶ Dois braços defendem simultaneamente: alto + médio.',
  '2. Giro dir 180° → Migi Age Uke + Hidari Soto Uke (Morote)',
  '3. Giro esq 90° → Juji Uke gedan (bloqueio cruzado baixo, punhos cruzados)',
  '  ▶ Juji: os dois punhos cruzam-se em "X" para bloquear chute baixo.',
  '4. Hiza Geri migi (joelhada)',
  '  ▶ Agarrar ombros do adversário; joelho ao estômago/costela.',
  '5. Kakiwake Uke (separação bilateral, mãos afastam)',
  '6. Empi/Hiji Ate (cotovelo ao rosto ou costela)',
  '7. Avança → Migi Oi Tsuki + Hidari Gyaku Tsuki · KIAI',
  '8. Giro esq 90° → Hidari Kakiwake Uke · kokutsu',
  '9. Hiza Geri hidari',
  '10. Empi Ate migi',
  '11. Nukite migi (mão lança ao plexo) · KIAI',
  '12–18. (retorno simétrico)',
  'Mawatte! — Yame!',
]},
{id:'k_tsuki',name:'Tsuki no Kata',belt:'amarela',time:'36s',
origin:'Pelo próprio nome: kata de socos. Apenas um chute em toda a forma.',
embusen:'M5,50 L55,50 M15,20 L45,80 M45,20 L15,80',
techs:['Seiken Chudan Tsuki','Seiken Jodan Tsuki','Seiken Gedan Tsuki','Tate Tsuki','Nukite','Mae Geri'],
note:'Objetivo: desenvolver potência nos socos em diferentes alturas e posturas.',
silences:'Quase sem chutes por design.',
steps:[
  'Yoi! — heisoku dachi · mãos em guarda',
  '1. Avança hidari → Migi Seiken Chudan Tsuki · zenkutsu',
  '2. Avança → Hidari Seiken Chudan Tsuki',
  '3. Avança → Migi Seiken Chudan Tsuki · KIAI',
  '4. Mawatte! → 3 Seiken Jodan Tsuki (soco ao rosto) · 3 passos',
  '  ▶ Jodan: punho mais alto, linha do nariz do oponente.',
  '5. Mawatte! → 3 Seiken Gedan Tsuki (soco baixo) · 3 passos',
  '  ▶ Gedan: punho ao plexo/abdômen. Postura mais baixa.',
  '6. Mawatte! → 3 Tate Tsuki (soco vertical, polegar para cima) · 3 passos',
  '7. Mawatte! → 3 Nukite (lança de dedos) · 3 passos · KIAI no último',
  '  ▶ Nukite: 4 dedos estendidos, palma para baixo, ao plexo solar.',
  '8. Mawatte! → Mae Geri chudan + Oi Tsuki chudan × 3',
  '  ▶ Único chute do kata: geri prepara; soco finaliza.',
  'Mawatte! — Yame!',
]},
{id:'k_pi5',name:'Pinan Sono Go',belt:'verde',time:'30s',
origin:'Primeiro kata com salto. Dominar os 5 Pinan é suficiente para defesa real.',
embusen:'M30,80 L30,50 M30,50 L5,20 M30,50 L55,20 M30,50 L30,10',
techs:['Tobi (salto)','Morote Uchi Uke','Shuto Osae Uke','Hiji Chudan Ate','Age Uke + Gyaku Tsuki'],
note:'O Tobi resolve o impasse de distância pelo ar. Morote Uchi Uke — dois braços simultâneos em vetores opostos. Encerra os cinco Pinan: quem domina todos está pronto para o kumite real.',
silences:'Sem técnicas de longa distância antes do salto. O Tobi pressupõe que o solo já foi esgotado — só o ar resolve o impasse restante.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Giro esq 90° → Hidari Age Uke + Migi Gyaku Tsuki · zenkutsu',
  '2. Giro dir 180° → Migi Age Uke + Hidari Gyaku Tsuki',
  '3. Giro esq 90° → Hidari Morote Uchi Uke (2 antebraços simultâneos para dentro)',
  '  ▶ Morote: dois braços defendem ao mesmo tempo, um de fora→dentro, outro ao contrário.',
  '4. Migi Yoko Geri chudan (kiba dachi)',
  '5. Migi Hiji Chudan Ate (cotovelo lateral ao estômago)',
  '6. Giro 90° dir → Hidari Shuto Osae Uke (mão faca pressiona para baixo) · kokutsu',
  '7. Avança → Migi Mae Geri + Migi Oi Tsuki',
  '8. Hidari Shuto Osae Uke · kokutsu',
  '9. Avança → Migi Mae Geri + Migi Oi Tsuki · KIAI',
  '10. TOBI! — salto com Migi Yoko Geri no ar (kiai)',
  '  ▶ Câmara, salto; pé lateral no ar com sokuto. Aterrissagem em kiba dachi.',
  '11. Retorno: Age Uke + Gyaku Tsuki × 2 (simetria)',
  'Mawatte! — Yame!',
]},
{id:'k_gekidai',name:'Gekisai Dai',belt:'verde',time:'47s',
origin:'Chojun Miyagi (Goju-ryu). Fluidez e mobilidade. Força através do movimento, não da rigidez.',
embusen:'M30,80 L30,55 M30,55 L5,30 M5,30 L55,30 M55,30 L30,55 M30,55 L30,10',
techs:['Mawashi Geri Jodan','Yoko Geri Jodan','Tettsui Uchi','Age Uke + Mae Geri'],
note:'Origem Goju-ryu: fluidez acima de rigidez. O embusen Norte→Sul inverte a expectativa — o kata que avança é o mesmo que retorna. Mobilidade como princípio fundamental.',
silences:'Sem postura fixa prolongada. A origem Goju-ryu rejeita a ancoragem rígida do Shuri-te — mobilidade é a defesa.',
steps:[
  'Yoi! — musubi dachi',
  '1. Giro esq 90° → Hidari Age Uke · zenkutsu',
  '2. Migi Seiken Jodan Tsuki (soco direto ao rosto)',
  '3. Giro dir 180° → Migi Age Uke · zenkutsu',
  '4. Hidari Seiken Jodan Tsuki',
  '5. Giro esq 90° → Hidari Age Uke · zenkutsu (eixo principal)',
  '6. Migi Mae Geri chudan',
  '7. Avança → Migi Oi Tsuki jodan · KIAI',
  '8. Mawashi Geri jodan migi (chute circular alto)',
  '  ▶ Quadril orbita; haisoku à têmpora. Jodan = arriscar, alto retorno.',
  '9. Migi Tettsui Hizo Uchi + Hidari Uraken Ganmen Uchi (simultâneos)',
  '10. Yoko Geri jodan hidari (chute lateral ao rosto)',
  '  ▶ Sokuto ao queixo — técnica de competição de alto nível.',
  '11. Hidari Tettsui + Migi Uraken (simultâneos)',
  '12. Retorno: Age Uke + Mae Geri + Oi Tsuki × 2 · KIAI final',
  'Mawatte! — Yame!',
]},
{id:'k_yantsu',name:'Yantsu',belt:'marrom',time:'62s',
origin:'Origem incerta, possivelmente Motobu Shito-ryu. Exigido no 1º Kyu marrom.',
embusen:'M30,80 L30,45 M30,45 L5,10 M30,45 L55,10',
techs:['Gyaku Tsuki (variações)','Uraken Shomen Uchi','Mae Geri','Shuto combinações'],
note:'Velocidade acima de força — Yantsu ensina que a hesitação é a única derrota real. Três direções de saída, todas com contra-ataque imediato.',
silences:'Sem câmaras lentas, sem bloqueios explícitos. Yantsu pressupõe que o timing foi internalizado — a resposta é o ataque direto, não a defesa.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Hidari Shuto Jodan Uke · kokutsu dachi',
  '  ▶ Mão faca bloqueio alto — o kakiwake lateral para mão aberta.',
  '2. Migi Mae Geri chudan',
  '3. Migi Seiken Chudan Gyaku Tsuki · zenkutsu',
  '4. Giro dir 45° (diag) → Migi Shuto Uke · kokutsu',
  '5. Hidari Mae Geri + Hidari Oi Tsuki',
  '6. Giro esq 90° → Hidari Shuto Uke · kokutsu (diagonal oposta)',
  '7. Migi Mae Geri + Migi Oi Tsuki · KIAI',
  '8. Retorno ao centro → Uraken Shomen Uchi migi (dorso do punho ao rosto)',
  '  ▶ Snap do pulso na chegada — velocidade, não força.',
  '9. Avança → Migi Gyaku Tsuki + Hidari Gyaku Tsuki (alternados rápidos)',
  '10. Avança → Renraku: Gyaku × 3 crescendo · KIAI',
  '11. Saída diag esq → Shuto Uke + Mae Geri + Gyaku Tsuki',
  '12. Saída diag dir → Shuto Uke + Mae Geri + Gyaku Tsuki · KIAI',
  'Mawatte! — Yame!',
]},
{id:'k_tensho',name:'Tensho',belt:'marrom',time:'2min19s',
origin:'Goju-ryu. Contraparte suave (yin) do Sanchin (yang). Oyama: kata mais indispensável.',
embusen:'M30,80 L30,10',
techs:['Shotei/Teisho','Mawashi Uke circular','Age/Otoshi Shotei','Hiki (puxar)'],
note:'Único kata inteiramente de mão aberta. Sem punho fechado. Respiração Ibuki.',
silences:'Zero técnicas de punho fechado.',
steps:[
  'Yoi! — sanchin dachi · respiração Ibuki 3 ciclos',
  '  ▶ Todo o kata é executado em sanchin dachi. Movimentos suaves + respiração contínua.',
  '1. Hidari Teisho Age (calcanhar da palma sobe)',
  '2. Migi Teisho Otoshi (calcanhar da palma desce)',
  '  ▶ Suave mas firme — a tensão chega no impacto, não antes.',
  '3. Mawashi Uke hidari (bloqueio circular completo): Jodan → Chudan → Gedan',
  '  ▶ O braço traça um círculo completo vertical — o kata yin.',
  '4. Migi Teisho Osae (pressiona para baixo)',
  '5. Mawashi Uke migi',
  '6. Hiki hidari + migi (puxar simulado das lapelas, dois braços)',
  '  ▶ Hiki: técnica de agarre — puxar adversário ao contra-ataque.',
  '7. Sequência central: Teisho Age + Otoshi × 3 (alternados)',
  '8. Teisho Chudan Mae (palma frontal ao tronco)',
  '9. Mawashi Uke completo × 3 (cada vez mais lento, mais respiração)',
  '10. Retorno com mesma sequência inversa',
  'Yame! — expiração longa · musubi dachi',
]},
{id:'k_gekisho',name:'Gekisai Sho',belt:'marrom',time:'48s',
origin:'Variação do Dai com mais técnicas de mão aberta.',
embusen:'M30,80 L30,55 M30,55 L5,30 M5,30 L55,30 M55,30 L30,55 M30,55 L30,10',
techs:['Haito Uchi','Nukite variações','Shotei','Shuto Uke variações'],
note:'Onde o Dai usa seiken, o Sho usa mão aberta. A mão aberta não é fraca — é precisa: Shuto corta, Haito rasga, Nukite penetra. A mesma forma, vocabulário invertido.',
silences:'Sem socos fechados. O punho cerrado é o silêncio do Sho — o seu par Dai já o disse tudo com seiken.',
steps:[
  'Yoi! — musubi dachi',
  '  ▶ Mesma estrutura do Gekisai Dai. Apenas as armas mudam: punho→mão aberta.',
  '1. Giro esq 90° → Hidari Shuto Jodan Uke · kokutsu (mão faca alta)',
  '2. Migi Mae Geri + Avança → Migi Nukite chudan',
  '  ▶ Nukite substituiu o Oi Tsuki do Dai.',
  '3. Giro dir 180° → Migi Shuto Jodan Uke · kokutsu',
  '4. Hidari Mae Geri + Hidari Nukite · KIAI',
  '5. Giro esq 90° → Haito Jodan Uchi (crista da mão ao rosto)',
  '  ▶ Haito: borda do indicador, lado interno da mão — rasgo ao pescoço.',
  '6. Shotei chudan (calcanhar da palma ao plexo)',
  '7. Mawashi Geri jodan migi · KIAI',
  '8. Retorno: Shuto Uke + Nukite + Haito × 2',
  '9. Yoko Geri jodan + Shotei Uchi × 2',
  'Mawatte! — Yame!',
]},
{id:'k_saifa',name:'Saifa',belt:'marrom',time:'43s',
origin:'Higaonna → Miyagi → Oyama. O kata que mais introduz técnicas ausentes do kihon.',
embusen:'M5,70 L30,30 L55,70 M30,30 L30,10',
techs:['Ura Tsuki','Haishu Uchi','Tettsui Uchi','Otoshi Empi','Mawashi Uke','Nidan Geri'],
note:'Saifa (破壊, "rasgar e destruir") opera no espaço mínimo. Ura Tsuki, Empi, Tettsui — todas armas de curta distância. O kata pressupõe que o adversário já está dentro.',
silences:'Sem técnicas de longa distância. Todo o combate acontece no espaço do abraço — o Saifa não tem distância de recuo.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Migi Ura Tsuki (soco invertido, uppercut curto)',
  '  ▶ Ura Tsuki: punho palma para cima, cotovelo quase reto. Distância mínima.',
  '3. Migi Haishu Uchi (dorso da mão aberta ao pescoço)',
  '4. Giro dir → Migi Gedan Barai + Hidari Ura Tsuki + Hidari Haishu Uchi',
  '5. Giro esq → centro: Mawashi Uke (bloqueio circular)',
  '  ▶ Mawashi Uke: o braço traça arco horizontal para deflectir soco circular.',
  '6. Otoshi Empi (cotovelo desce sobre ombro/crânio adversário)',
  '  ▶ Agarrar cabeça; cotovelo desce como martelo.',
  '7. Tettsui Hizo Uchi (punho martelo à costela)',
  '8. Nidan Geri (chute duplo em voo: mae + yoko no ar)',
  '  ▶ Primeira perna chuta, ainda no ar a segunda perna chuta — KIAI.',
  '9. Aterrissa em zenkutsu → Migi Oi Tsuki · KIAI',
  '10. Retorno: Gedan Barai + Ura Tsuki + Haishu × 2',
  'Mawatte! — Yame!',
]},
{id:'k_kanku',name:'Kanku',belt:'shodan',time:'1min40s',
origin:'Kusanku/Kushanku, séculos XVI-XVII. O kata mais longo e completo dos kata do Norte.',
embusen:'M30,5 L55,30 L30,55 L5,30 Z M30,5 L30,55 M5,30 L55,30',
techs:['Repertório completo: todos os socos, uchi, geri, uke. Nukite, tobi.'],
note:'Abertura icônica: mãos formam losango apontando ao céu — 看空 "ver o vazio". O kata mais longo sintetiza todo o vocabulário; dominá-lo é dominar a linguagem. O primeiro kata do Shodan é o primeiro ato de síntese.',
silences:'Poucas pausas — o Kanku não descansa. O kata que inclui quase tudo interroga, por contraste, tudo o que foi excluído do restante do currículo.',
steps:[
  'Yoi! — musubi dachi',
  '1. ABERTURA: mãos sobem formando losango apontando ao céu (看空)',
  '  ▶ Olhar pelo centro do losango. Pausa de 3 segundos. Mãos descem.',
  '2. Gedan Barai × 2 (L+R) · zenkutsu',
  '3. Jodan Age Uke × 2 · kokutsu dachi',
  '4. Gyaku Tsuki chudan × 2',
  '5. Shuto Mawashi Uke × 2 · kokutsu',
  '6. Mae Geri × 2 + Oi Tsuki × 2',
  '7. Empi Ate × 2 (cotovelo lateral)',
  '8. Uraken Jodan Uchi × 2',
  '9. Mae Geri + Migi Oi Tsuki · KIAI',
  '10. Mawashi Geri jodan × 2',
  '11. Yoko Geri chudan × 2 (kiba dachi)',
  '12. Nukite chudan × 2',
  '13. Tettsui × 2 + Shuto × 2',
  '14. TOBI! — Nidan Geri no ar · KIAI',
  '  ▶ Salto máximo; dois chutes; aterrissagem controlada.',
  '15. Uke variações: Soto, Uchi, Age, Gedan Barai × 2 cada',
  '16. Fechar: losango ao céu (espelho da abertura) · pausa · Yame!',
  'Mawatte! — Yame!',
]},
{id:'k_seien',name:'Seienchin',belt:'shodan',time:'1min24s',
origin:'Naha-te. Kata longo em Shiko Dachi baixo. Desenvolve força e estabilidade nos membros inferiores.',
embusen:'M10,50 Q30,10 50,50 Q30,90 10,50',
techs:['Seiken Tsuki','Ura Tsuki','Hiji Ate (todas direções)','Age Uke + Gedan Barai','Mawashi Empi'],
note:'SEM NENHUM CHUTE. Kata avançado inteiramente de te-waza. Filosofia de combate de curta distância.',
silences:'Zero geri. Zero keage. Silêncio radical e intencional.',
steps:[
  'Yoi! — musubi dachi',
  '  ▶ NENHUM chute em todo o kata. Apenas te-waza em shiko dachi baixo.',
  '1. Abertura: mãos formam triângulo à frente · pausa',
  '2. Giro esq → Hidari Age Uke + Migi Gedan Barai (simultâneos) · shiko dachi',
  '  ▶ Shiko dachi: pés 45° para fora, joelhos bem dobrados, costas retas.',
  '3. Migi Ura Tsuki (uppercut) + Hidari Gyaku Tsuki',
  '4. Mawashi Empi migi (cotovelo circular ao rosto)',
  '5. Avanço diagonal → Hiji Ate (cotovelo) em 4 direções: jodan, chudan, gedan, ushiro',
  '  ▶ Cotovelo é a arma do espaço mínimo — alcance de abraço.',
  '6. Retorno centro → Age Uke × 2 + Gedan Barai × 2 (simultâneos)',
  '7. Avança 3 passos: Oi Tsuki chudan + Gyaku Tsuki jodan alternados',
  '8. Giro dir → mesma sequência de cotovelos + uke',
  '9. Centro: Morote Tsuki (dois socos simultâneos)',
  '10. Sequência final: Age Uke + Gedan Barai + Mawashi Empi × 3 · KIAI',
  'Mawatte! — Yame!',
]},
{id:'k_garyu',name:'Garyu',belt:'shodan',time:'38s',
origin:'Criado por Mas Oyama. Garyu = dragão reclinado. Nome é pseudônimo de Oyama.',
embusen:'M5,70 L30,30 M30,30 L55,70 M30,30 L30,10',
techs:['Shuto combinações','Mae Geri','Yoko Geri','Seiken Tsuki','Uraken variações'],
note:'Garyu (臥龍, "dragão reclinado") é o kata pessoal de Oyama — limpo, técnico, sem ornamento. O dragão reclinado não está derrotado: está aguardando. Transição para o vocabulário avançado com máxima eficiência.',
silences:'Sem técnicas do Sanchin ou Tensho — sem isometria, sem contemplação. Garyu é eficiência direta: o kata do fundador não tem tempo para o que não é necessário.',
steps:[
  'Yoi! — heisoku dachi',
  '1. Saída diag esq → Hidari Shuto Jodan Uke · kokutsu dachi',
  '2. Migi Mae Geri + Hidari Oi Tsuki chudan · zenkutsu',
  '3. Saída diag dir → Migi Shuto Jodan Uke · kokutsu',
  '4. Hidari Mae Geri + Migi Oi Tsuki · KIAI',
  '5. Retorno ao centro (norte) → Hidari Uraken Jodan Uchi',
  '  ▶ Uraken: dorso do punho ao rosto — velocidade de snap.',
  '6. Avança → Migi Seiken Chudan Tsuki + Hidari Gyaku Tsuki',
  '7. Migi Yoko Geri chudan · kiba dachi',
  '8. Avança → Hidari Seiken + Migi Gyaku',
  '9. Saída diag esq-frente → Hidari Shuto Uke + Migi Mae Geri + Migi Gyaku',
  '10. Saída diag dir-frente → Migi Shuto Uke + Hidari Mae Geri + Hidari Gyaku · KIAI',
  'Mawatte! — Yame!',
]},
{id:'k_seipai',name:'Seipai',belt:'shodan',time:'46s',
origin:'Higaonna → Miyagi → Oyama. 18 = 6×3 (fórmula budista). Duros e suaves, longa e curta distância.',
embusen:'M5,50 L55,50 M30,5 L30,55 M10,10 L50,50 M50,10 L10,50',
techs:['Empi (todas direções)','Shotei/Teisho','Shuto variações','Geri combinações'],
note:'Seipai (十八, "dezoito") tem 18 tempos sem simetria previsível. Inclui entradas de grappling sem nome no kihon — nem toda técnica eficaz cabe no vocabulário oficial.',
silences:'Sem padrão de simetria previsível — os 18 tempos não se repetem. Seipai ensina que o combate real não tem roteiro.',
steps:[
  'Yoi! — heisoku dachi · respiração centrada',
  '  ▶ 18 tempos sem simetria. Não há "retorno" — o combate real não volta atrás.',
  '1. Giro esq 90° → Hidari Gedan Barai · zenkutsu',
  '2. Migi Empi jodan (cotovelo alto ao rosto)',
  '  ▶ Empi = o cotovelo. Todas as direções: mae, yoko, ushiro, age, otoshi.',
  '3. Hidari Shotei Osae (palma pressiona para baixo)',
  '4. Giro dir → Migi Shuto Jodan Uke · kokutsu',
  '5. Hidari Mae Geri + Migi Oi Tsuki',
  '6. Giro esq → Empi Chudan (cotovelo lateral ao tronco)',
  '7. Migi Mawashi Geri chudan · KIAI',
  '8. Entrada curta: Ura Tsuki + Empi Ushiro (cotovelo para trás)',
  '9. Teisho/Shotei em 3 direções: age, mae, otoshi',
  '10. Shuto Uke × 2 + Nukite (técnica de finalização)',
  '11. Geri combinações: Mae + Mawashi + Yoko (3 pernas consecutivas)',
  '12. Fechar: Empi otoshi (cotovelo descendo) · KIAI · pausa',
  'Yame!',
]},
];

const RENRAKU=[
{id:'r01',name:'Gedan Barai + Oi Tsuki',belt:'branca',
steps:['Gedan Barai — Hajime!','  ▶ Avança em Zenkutsu Dachi, antebraço varre do ouvido à coxa','  ▶ Seiken Chudan Oi Tsuki — golpe frontal ao tronco','  ▶ Yame! Mawatte! Hajime!'],
note:'A combinação fundamental. Defesa → Ataque. Dois tempos.'},
{id:'r02',name:'Jodan Uke + Gyaku Tsuki',belt:'branca',
steps:['Jodan Uke — Hajime!','  ▶ Antebraço sobe, bloqueio alto','  ▶ Seiken Chudan Gyaku Tsuki — soco reverso ao tronco','  ▶ Yame! Mawatte!'],
note:'O quadril gira duas vezes — uma para bloquear, outra para socar. Base do jiyu kumite.'},
{id:'r03',name:'Mae Geri + Gyaku Tsuki',belt:'laranja',
steps:['Mae Geri — Hajime!','  ▶ Câmara: joelho sobe. Chusoku ao chudan','  ▶ Seiken Chudan Gyaku Tsuki','  ▶ Yame! Mawatte!'],
note:'Primeiro renraku mão+pé. O chute abre espaço, o soco fecha.'},
{id:'r04',name:'Mawashi Geri + Gyaku Tsuki',belt:'laranja',
steps:['Mawashi Geri — Hajime!','  ▶ Câmara diagonal. Quadril abre. Chusoku circular','  ▶ Seiken Chudan Gyaku Tsuki imediatamente ao pousar','  ▶ Yame! Mawatte!'],
note:'Velocidade do quadril no Mawashi carrega diretamente para o Gyaku Tsuki.'},
{id:'r05',name:'Jodan Uke + Mae Geri + Gyaku Tsuki',belt:'azul',
steps:['Jodan Uke + Mae Geri + Gyaku Tsuki — Hajime!','  ▶ Jodan Uke: bloqueio alto','  ▶ Mae Geri: chute frontal com a perna da frente','  ▶ Gyaku Tsuki: soco reverso ao pousar','  ▶ Yame! Mawatte!'],
note:'Primeiro renraku de 3 tempos. Uke → Geri → Tsuki. Defesa → Distância → Fechamento.'},
{id:'r06',name:'Gedan Barai + Mawashi Geri + Gyaku Tsuki',belt:'azul',
steps:['Gedan Barai + Mawashi Geri + Gyaku Tsuki — Hajime!','  ▶ Gedan Barai: varredura baixa','  ▶ Mawashi Geri: chute circular ao jodan ou chudan','  ▶ Gyaku Tsuki: soco reverso','  ▶ Yame! Mawatte!'],
note:'Varredura baixa cria abertura para o chute circular.'},
{id:'r07',name:'Chudan Soto Uke + Gyaku Tsuki + Mae Geri',belt:'azul',
steps:['Chudan Soto Uke + Gyaku Tsuki + Mae Geri — Hajime!','  ▶ Soto Uke: bloqueio externo','  ▶ Gyaku Tsuki: soco reverso imediato','  ▶ Mae Geri: chute frontal para encerrar','  ▶ Yame! Mawatte!'],
note:'O Soto Uke abre a guarda do oponente para o Gyaku Tsuki.'},
{id:'r08',name:'Mae Geri + Jodan Uke + Uraken + Gyaku Tsuki',belt:'amarela',
steps:['Mae Geri + Jodan Uke + Uraken + Gyaku Tsuki — Hajime!','  ▶ Mae Geri: chute frontal','  ▶ Jodan Uke: bloqueio alto ao avançar','  ▶ Uraken Gammen Uchi: chicote ao rosto','  ▶ Gyaku Tsuki: soco reverso','  ▶ Yame! Mawatte!'],
note:'Renraku de 4 tempos. Introduce Uraken em combinação.'},
{id:'r09',name:'Yoko Geri + Gyaku Tsuki',belt:'azul',
steps:['Yoko Geri + Gyaku Tsuki — Hajime!','  ▶ Câmara lateral: joelho aponta para baixo','  ▶ Yoko Geri: sokuto lateral ao tronco','  ▶ Gyaku Tsuki ao pousar','  ▶ Yame! Mawatte!'],
note:'Câmara do yoko geri: joelho aponta para baixo antes de estender. Erro comum: joelho apontar para cima.'},
{id:'r10',name:'Mawashi Geri + Ushiro Geri + Gyaku Tsuki',belt:'verde',
steps:['Mawashi Geri + Ushiro Geri + Gyaku Tsuki — Hajime!','  ▶ Mawashi Geri: circular ao chudan','  ▶ Ushiro Geri: calcanhar para trás (mesma perna ou alternada)','  ▶ Gyaku Tsuki ao pousar','  ▶ Yame! Mawatte!'],
note:'Ushiro Geri exige rotação de 180° do quadril. Manter alinhamento após a rotação.'},
{id:'r11',name:'Jodan Uke + Empi + Uraken + Gyaku Tsuki',belt:'verde',
steps:['Jodan Uke + Empi + Uraken + Gyaku Tsuki — Hajime!','  ▶ Jodan Uke','  ▶ Mae Empi: cotovelada frontal ao plexo solar','  ▶ Uraken Gammen Uchi: chicote ao rosto','  ▶ Gyaku Tsuki: fechamento','  ▶ Yame! Mawatte!'],
note:'Sequência de entrada: bloqueio → penetra → chicote → soco. Cada golpe mais próximo que o anterior.'},
{id:'r12',name:'Tobigeri (Mae Tobi Geri)',belt:'marrom',
steps:['Mae Tobi Geri — Hajime!','  ▶ Passo de impulso','  ▶ Joelho de impulso sobe, perna de ataque dispara chusoku no ar','  ▶ Pousar em Zenkutsu Dachi','  ▶ Gyaku Tsuki imediato ao pousar','  ▶ Yame! Mawatte!'],
note:'Primeiro tobi no currículo. O impulso vem da perna oposta. O Gyaku Tsuki ao pousar é obrigatório no exame.'},
// Verde — footwork de kumite
{id:'r13',name:'Okuri-ashi + Oi Tsuki',belt:'verde',cat:'ido',
steps:['Okuri-ashi Oi Tsuki — Hajime!','  ▶ Kamae: posição de kumite','  ▶ Okuri-ashi: pé da frente avança, pé de trás acompanha deslizando (sem cruzar)','  ▶ Oi Tsuki chudan ao chegar — quadril projeta junto ao deslize','  ▶ Mawatte! Okuri-ashi reverso. Yame!'],
note:'O deslize mantém o centro baixo e estável. Erro comum: pé de trás bate no de frente antes do soco.'},
{id:'r14',name:'Kosa-ashi + Mawashi Geri + Gyaku Tsuki',belt:'verde',cat:'ido',
steps:['Kosa-ashi + Mawashi Geri — Hajime!','  ▶ Kosa-ashi: pé de trás cruza à frente do outro (passo cruzado diagonal)','  ▶ A rotação do kosa pré-carrega o quadril para o circular','  ▶ Mawashi Geri chudan ou jodan','  ▶ Gyaku Tsuki ao pousar','  ▶ Yame! Mawatte!'],
note:'O kosa-ashi carrega o quadril para o Mawashi. Diferente do okuri: há cruzamento real dos pés.'},
{id:'r15',name:'Fumi-dashi + Yoko Geri + Uraken',belt:'verde',cat:'ido',
steps:['Fumi-dashi + Yoko Geri — Hajime!','  ▶ Fumi-dashi: passo largo diagonal 45° para fora da linha de ataque (tai sabaki)','  ▶ Yoko Geri: sokuto lateral ao chudan do oponente','  ▶ Uraken Shomen Uchi ao pousar','  ▶ Yame! Mawatte!'],
note:'Fumi-dashi é tai sabaki básico — sair da linha de ataque ao contra-atacar. Base do kumite defensivo.'},
// Marrom — movimentação avançada
{id:'r16',name:'Oi-ashi + Mae Geri + Mawashi Geri Jodan',belt:'marrom',cat:'ido',
steps:['Oi-ashi + Nidan Geri — Hajime!','  ▶ Oi-ashi: passo de perseguição (pé de trás empurra pé da frente explosivamente)','  ▶ Mae Geri chudan: câmara, chute, retorna — sem pousar','  ▶ Mawashi Geri jodan com a mesma perna (nidan geri)','  ▶ Gyaku Tsuki ao pousar','  ▶ Yame! Mawatte!'],
note:'Oi-ashi reduz a distância explosivamente. O nidan (dois chutes da mesma perna) aparece no Saifa kata.'},
{id:'r17',name:'Tenshin + Gyaku Tsuki + Ura Mawashi',belt:'marrom',cat:'ido',
steps:['Tenshin + Contra-ataque — Hajime!','  ▶ Tenshin (転身): passo de recuo em ângulo 45° atrás e para o lado, saindo da linha','  ▶ Imediatamente: Gyaku Tsuki ao centro aberto do oponente','  ▶ Ura Mawashi Geri jodan: chute gancho de calcanhar','  ▶ Yame! Mawatte!'],
note:'Tenshin = transformar o corpo. Não é recuo — é posicionamento estratégico. Presente no Yantsu kata.'},
{id:'r18',name:'Gedan Barai + Yoko Geri + Uraken + Gyaku Tsuki',belt:'amarela',
steps:['Gedan Barai + Yoko Geri — Hajime!',
  '  ▶ Gedan Barai: varredura baixa, abre a guarda do oponente',
  '  ▶ Câmara lateral: joelho aponta para o chão',
  '  ▶ Yoko Geri sokuto ao chudan',
  '  ▶ Uraken Shomen Uchi ao pousar',
  '  ▶ Gyaku Tsuki: fechamento',
  '  ▶ Yame! Mawatte!'],
note:'Defesa baixa → lateral → chicote → soco. Quatro alturas distintas em quatro tempos. Coordena os dois eixos posicionais num único renraku.'},
{id:'r19',name:'Soto Uke + Empi + Uraken + Mae Geri + Gyaku Tsuki',belt:'shodan',
steps:['Soto Uke + 5 tempos — Hajime!',
  '  ▶ Soto Uke: bloqueio externo, abre a guarda',
  '  ▶ Mae Empi: cotovelada frontal ao plexo — penetra a distância',
  '  ▶ Uraken Gammen Uchi: chicote ao rosto, alcance de cotovelo',
  '  ▶ Mae Geri chudan: cria distância de saída',
  '  ▶ Gyaku Tsuki: fecha ao pousar',
  '  ▶ Yame! Mawatte!'],
note:'Cinco tempos, cinco armas: antebraço → cotovelo → dorso do punho → chusoku → seiken. O renraku completo do kumite — o padrão de entrada, controle e saída.'},
{id:'r20',name:'Ushiro Mawashi Geri + Jodan Mawashi Geri + Gyaku Tsuki',belt:'shodan',
steps:['Nidan Rotacional — Hajime!',
  '  ▶ Rotação 360°: Ushiro Mawashi Geri — calcanhar ao jodan',
  '  ▶ Continuação sem pousar: Mawashi Geri jodan com a mesma perna',
  '  ▶ Gyaku Tsuki ao aterrissar com kiai',
  '  ▶ Yame! Mawatte!'],
note:'Dois chutes da mesma perna em rotação completa. Requer equilíbrio de Shodan. Exclusivo da faixa preta — proibido nos graus kyu.'},
{id:'r21',name:'Tenshin + Ashi Barai + Otoshi Empi',belt:'shodan',
steps:['Yakusoku Kumite — Hajime!',
  '  ▶ Tenshin 45°: recuar em ângulo, sair da linha de ataque',
  '  ▶ Oi Tsuki imediato ao flanco descoberto',
  '  ▶ Ashi Barai: varredura de pé, desequilibra o oponente',
  '  ▶ Otoshi Empi: cotovelada descendente ao oponente desequilibrado',
  '  ▶ Kiai! — Yame! Naore! Rei!'],
note:'Padrão de yakusoku kumite do Shodan: Tenshin + Barai + finalização. Requer uke (parceiro) nos exames IKO1. A trilogia do combate eficiente.'},
];

const BELT_REQ={
branca:{exam:'Técnica única em Zenkutsu. Gedan Barai + Oi Tsuki. Kata: Taikyoku I, II e Sokugi I, II.',ido:'6–8 golpes, técnica única repetida',min:0},
laranja:{exam:'Taikyoku I-III, Sokugi I-III. Renraku básico (2 técnicas). Kihon geiko em Zenkutsu.',ido:'8–10 golpes, renraku simples',min:0},
azul:{exam:'Pinan I, II, III. Sanchin no Kata. Ido-Geiko com Kiba Dachi e Kokutsu.',ido:'10–15 golpes, 3 renraku distintos',min:0},
amarela:{exam:'Pinan I-IV. Tsuki no Kata. Kaiten Ido (360°). Renraku de 3 técnicas.',ido:'15–20 golpes, alternância mão/pé',min:0},
verde:{exam:'Pinan I-V. Gekisai Dai. Footwork de kumite: okuri-ashi, fumi-dashi, kosa-ashi. Renraku de 3–4 técnicas com deslocamento.',ido:'20–25 golpes · footwork: okuri, fumi, kosa · variação de altura e distância',min:0},
marrom:{exam:'Yantsu, Tensho, Gekisai Sho, Saifa. Yakusoku Kumite. Tenshin, oi-ashi, nidan geri. Tameshiwari 1-2 tábuas.',ido:'25–30 golpes · tai sabaki · renraku de 4+ técnicas com movimentação',min:0},
shodan:{exam:'Kanku, Seienchin, Garyu, Seipai. 10 lutas de 3min. Tameshiwari 3 tábuas. Teoria: nota mínima 7. Ido-Geiko: mínimo 30 golpes.',ido:'Mínimo 30 golpes (requisito CBKKO/IKO1)',min:30},
};

// Node lookup
const NMAP=Object.fromEntries(NODES.map(n=>[n.id,n]));
const TMAP=Object.fromEntries(TECHS.map(t=>[t.id,t]));

// Platonic solid shape config per node type
// Grammar → Geometry: acao=Fire/Tetrahedron, dachi=Earth/Cube, direcao=Air/Octahedron,
// ido=Water/Icosahedron, alvo=Aether/Dodecahedron, buki_mao=Hexagon(Fire+Earth), buki_pe=Diamond
const SHAPE_CFG={
  acao:    {sides:3,rot:-30, star:false,outerR:1.55},
  dachi:   {sides:4,rot:45,  star:false,outerR:1.45},
  direcao: {sides:8,rot:22.5,star:false,outerR:1.35},
  ido:     {sides:5,rot:0,   star:true, outerR:1.5},
  alvo:    {sides:5,rot:-18, star:false,outerR:1.45},
  buki_mao:{sides:6,rot:0,   star:false,outerR:1.4},
  buki_pe: {sides:4,rot:0,   star:false,outerR:1.5},
};

/// Ido canonical map: techniques that use okuri (rotational/lateral) or tobi (jumping)
// All others default to ayumi (normal step)
const IDO_MAP={
  t10:'okuri',t22:'okuri',t23:'okuri',t24:'okuri',t27:'okuri',
  t29:'okuri',t30:'okuri',t31:'okuri',t36:'okuri',t37:'okuri',t39:'okuri',
  k07:'okuri',
  k05:'tobi', // Nidan Geri — only jumping technique
};
function getIdo(techId){return IDO_MAP[techId]||'ayumi';}

// Degree: how many techniques reference each node (visual weight in constellation)
const NODE_DEGREE=(()=>{
  const d={};
  TECHS.forEach(t=>{
    t.nodes.forEach(nid=>{d[nid]=(d[nid]||0)+1;});
    if(t.dachi)d[t.dachi]=(d[t.dachi]||0)+1;
    const idoId=getIdo(t.id);
    d[idoId]=(d[idoId]||0)+1;
  });
  return d;
})();
const _maxDeg=Math.max(...Object.values(NODE_DEGREE));

// Build edges for constellation: star from nodes[0] (hub=buki) to all semantic dimensions
