"""
ABM Policy Citation Network Analysis

A tool for analyzing policy citations of research on agent-based models (ABM)
using Overton and OpenAlex APIs.
"""

__version__ = "1.0.0"
__author__ = "Generated by Claude"
